
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class resources : Luban.BeanBase
{
    public resources(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["resources_name"].IsString) { throw new SerializationException(); }  ResourcesName = _buf["resources_name"]; }
        { if(!_buf["resources_describe"].IsString) { throw new SerializationException(); }  ResourcesDescribe = _buf["resources_describe"]; }
        { if(!_buf["resources_picture"].IsString) { throw new SerializationException(); }  ResourcesPicture = _buf["resources_picture"]; }
    }

    public static resources Deserializeresources(JSONNode _buf)
    {
        return new resources(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string ResourcesName;
    /// <summary>
    /// 资源说明
    /// </summary>
    public readonly string ResourcesDescribe;
    /// <summary>
    /// 资源图片
    /// </summary>
    public readonly string ResourcesPicture;
   
    public const int __ID__ = -1983070683;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "resourcesName:" + ResourcesName + ","
        + "resourcesDescribe:" + ResourcesDescribe + ","
        + "resourcesPicture:" + ResourcesPicture + ","
        + "}";
    }
}
}

