
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 游戏资源表
/// </summary>
public partial class Tbresources
{
    private readonly System.Collections.Generic.Dictionary<int, resources> _dataMap;
    private readonly System.Collections.Generic.List<resources> _dataList;
    
    public Tbresources(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, resources>(count);
        _dataList = new System.Collections.Generic.List<resources>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resources _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resources.Deserializeresources(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resources> DataMap => _dataMap;
    public System.Collections.Generic.List<resources> DataList => _dataList;

    public resources GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public resources Get(int key) => _dataMap[key];
    public resources this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

